### ISSUE TITLE
[bug] <title>

### ISSUE THREAD

**Issue by piersdd** [siderolabs/omni-feedback#45]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current Behavior

When installing Talos Linux arm64 virtualised on macOS Apple Silicon, using QEMU via [UTM](https://mac.getutm.app) which "employs Apple's Hypervisor virtualization framework"

The node registers, mislabelled, with Omni as `platform:metal`

otherwise.. works a treat! thankyou

### Expected Behavior

The node registers, labelled; `platform:QEMU` or somesuch

### Steps To Reproduce

On M1 or M2 Apple Mac, utilise Apple's Hypervisor virtualization framework, with https://github.com/utmapp/UTM

Provision new virtualised QEMU instance using Omni downloaded arm64.iso

### What browsers are you seeing the problem on?

Safari

**Comment by smira** [comment]
The `metal` platform is a Talos way to call where it runs. Other platforms are `aws`, `gcp`, etc. So it's expected that bare-metal, VMs use a generic `metal` platform. It defines more the way the node boots up, acquires the machine config, rather than the hardware it runs on. Hardware is described via SMBIOS data, which might or might not be available in your case.

**Comment by piersdd** [comment]
understood.
thanks
