### ISSUE TITLE
[feature] So why make omni now closed source?

### ISSUE THREAD

**Issue by LNAhri** [siderolabs/omni-feedback#8]
### Problem Description

Im just curious and looking through talos and omni. I really like the ideas your having but find it weird that everything you did until now was there as a open souce project and omni is now basically renamed theila with more integrations.

So will omni be always closed source or is this just until the beta a thing? 

Thanks for answering :)

**Comment by andrewrynhard** [comment]
Omni is far from just a rename of Theila. Theila was a simple informational UI while Omni is a full blown management solution. Yes we took some initial designs from Theila to save time but Omni is a lot more than just a rename and some integrations.

We chose to make Omni closed source so that the company can stay around and provide all the other things we do for free. This is the first and only project we have that is closed source.

**Comment by steverfrancis** [comment]
A lot of companies and people use Talos and Sidero Metal. The amount of customers paying for support for the open source projects Talos and SIdero Metal was... not zero, but pretty close. 
Companies are comfortable paying for SaaS products, like Omni, so we as a company can actually maintain Talos.

And, as Andrew notes, Omni is an awful lot more than the old UI, Theila, and a lot more complex - but is designed so it seems (and is, to the users) very simple...
